/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyDemoApp;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        ArrayList<Integer> a=new ArrayList<>();
        System.out.println(containsPar(a, 5, 6, 7));

    }
    public static String containsPar(ArrayList<Integer> array,int a,int b,int c){
        if(array.size()<1) return "Empty array";

        if(a==b || a==c || b==c) return "Same parameters!Parameters have to be unique";
        String result="";
        int count=0;
        for (Integer i : array) {
            if(i==a){
                count++;
                result=result+i+" ";
            }
            if(i==b){
                count++;
                result=result+i+" ";
            }
            if(i==c){
                count++;
                result=result+i+" ";
            }      
        }
        if(count==0) return "No match";

        
        return "Number(s) is/are in the array:"+result;
    }
}
