/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyDemoApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test

    public void testContainsAll() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
       assertEquals("Number(s) is/are in the array:"+1+" "+2+" "+3+" ",App.containsPar(array, 1, 2, 3)); 
    }

    @Test

    public void testContain() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
       assertEquals("Number(s) is/are in the array:"+1+" "+2+" ",App.containsPar(array, 1, 2, 5)); 
    }
    @Test

    public void testSamePar() {
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
        assertEquals("Same parameters!Parameters have to be unique",App.containsPar(array, 1, 2, 2)); 
     }

    @Test

    public void testEmptyArr() {
       ArrayList<Integer> array = new ArrayList<>();
       assertEquals("Empty array",App.containsPar(array, 1, 2, 3)); 
    }

    @Test

    public void testNoMatch() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
       assertEquals("No match",App.containsPar(array, 5, 6, 7)); 
    }

 
}
